/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.presentacion.empresa;

import com.dominio.EmpresaTransportista;
import org.itson.presentacion.InicioForm;

/**
 *
 * @author arace
 */
public class PrincipalEmpresaForm extends javax.swing.JFrame {

    private EmpresaTransportista empresa;
    private static PrincipalEmpresaForm form;
    /**
     * Creates new form PrincipalEmpresa
     */
    private PrincipalEmpresaForm() {
        initComponents();
    }
    
    public static PrincipalEmpresaForm getInstance(){
        if(form == null){
            form = new PrincipalEmpresaForm();
        }
        
        return form;
    }
    
    public void iniciarComponentes(){
        this.abrirVentana();
    }
    
    private void cerrarVentana(){
        this.setVisible(false);
    }
    
    private void abrirVentana(){
        this.setVisible(true);
    }
    
    private void abrirRegistroTraslado() {
        RegistrarTrasladoEmpresaForm registrarTraslado = null;
        registrarTraslado = RegistrarTrasladoEmpresaForm.getInstance();
        registrarTraslado.setEmpresaTransportista(empresa);
        registrarTraslado.iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        registarEmpresaBtn = new javax.swing.JButton();
        registrarTrasladoBtn = new javax.swing.JButton();
        regsarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 155, 71));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Bienvenido al menu principal de empresa ");

        registarEmpresaBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registarEmpresaBtn.setText("Registrar Empresa");
        registarEmpresaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarEmpresaBtnActionPerformed(evt);
            }
        });

        registrarTrasladoBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registrarTrasladoBtn.setText("Registrar Traslado");
        registrarTrasladoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarTrasladoBtnActionPerformed(evt);
            }
        });

        regsarBtn.setText("Regresar");
        regsarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regsarBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 30)); // NOI18N
        jLabel1.setText("Empresa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registrarTrasladoBtn)
                            .addComponent(registarEmpresaBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regsarBtn)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(234, 234, 234))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(registarEmpresaBtn)
                .addGap(48, 48, 48)
                .addComponent(registrarTrasladoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(regsarBtn)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarTrasladoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarTrasladoBtnActionPerformed
        this.abrirRegistroTraslado();
        this.setVisible(false);
    }//GEN-LAST:event_registrarTrasladoBtnActionPerformed

    private void regsarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regsarBtnActionPerformed
        InicioForm a= new InicioForm();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_regsarBtnActionPerformed

    private void registarEmpresaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarEmpresaBtnActionPerformed
        RegistrarEmpresaForm c  = new RegistrarEmpresaForm();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_registarEmpresaBtnActionPerformed

    public EmpresaTransportista getEmpresa() {
        return empresa;
    }

    public void setEmpresa(EmpresaTransportista empresa) {
        this.empresa = empresa;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton registarEmpresaBtn;
    private javax.swing.JButton registrarTrasladoBtn;
    private javax.swing.JButton regsarBtn;
    // End of variables declaration//GEN-END:variables
}
