
package org.itson.presentacion.Productor;

import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.itson.presentacion.InicioForm;

/**
 *
 * @author arace
 */
public class RegistrarProductorForm extends javax.swing.JFrame {
    private final String NOMBRE_PRODUCTOR = "Productor";
    private static final String CORREO_DEFAULT = "info@ejemplo.com";
    private static final String CONTRASENA_DEFAULT = "123456789112345";
    

    
    public RegistrarProductorForm() {
        initComponents();
    }
     private void iniciarComponentes() {
        this.campoClaveProductor.setEchoChar('•');
        this.campoConfirmarClaveProductor.setEchoChar('•');
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        registroProductorlbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        correoElectronicoLbl = new javax.swing.JLabel();
        contrasenaLbl = new javax.swing.JLabel();
        confirmarContrasenaLbl = new javax.swing.JLabel();
        campoClaveProductor = new javax.swing.JPasswordField();
        campoConfirmarClaveProductor = new javax.swing.JPasswordField();
        separador1 = new javax.swing.JSeparator();
        separado2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        registrarProductorBtn = new javax.swing.JButton();
        regresarBtn = new javax.swing.JButton();
        campoCorreoProductor = new javax.swing.JTextField();
        separador3 = new javax.swing.JSeparator();
        correoValidoLbl = new javax.swing.JLabel();
        contrasenaValidaLbl = new javax.swing.JLabel();
        campoNombreProductor = new javax.swing.JTextField();
        checkVisibleContrasena = new javax.swing.JCheckBox();
        checkVisibleContrasena1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        registroProductorlbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registroProductorlbl.setText("Registro Productor");

        nombreLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombreLbl.setText("Nombre:");

        correoElectronicoLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        correoElectronicoLbl.setText("Correo electronico: ");

        contrasenaLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contrasenaLbl.setText("Contraseña: ");

        confirmarContrasenaLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmarContrasenaLbl.setText("Confirmar contraseña: ");

        campoClaveProductor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoClaveProductor.setForeground(Color.GRAY);
        campoClaveProductor.setText(this.CONTRASENA_DEFAULT);
        campoClaveProductor.setBorder(null);

        campoConfirmarClaveProductor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoConfirmarClaveProductor.setForeground(Color.GRAY);
        campoConfirmarClaveProductor.setText(CONTRASENA_DEFAULT);
        campoConfirmarClaveProductor.setBorder(null);

        registrarProductorBtn.setBackground(new java.awt.Color(0, 0, 0));
        registrarProductorBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registrarProductorBtn.setForeground(new java.awt.Color(255, 255, 255));
        registrarProductorBtn.setText("Registrarme");
        registrarProductorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductorBtnActionPerformed(evt);
            }
        });

        regresarBtn.setBackground(new java.awt.Color(0, 0, 0));
        regresarBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        regresarBtn.setLabel("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        campoCorreoProductor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCorreoProductor.setForeground(Color.GRAY);
        campoCorreoProductor.setText(this.CORREO_DEFAULT);
        campoCorreoProductor.setBorder(null);
        campoCorreoProductor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCorreoProductorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCorreoProductorFocusLost(evt);
            }
        });
        campoCorreoProductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCorreoProductorMouseClicked(evt);
            }
        });

        campoNombreProductor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNombreProductor.setForeground(Color.GRAY);
        campoNombreProductor.setText(this.NOMBRE_PRODUCTOR);
        campoNombreProductor.setBorder(null);
        campoNombreProductor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreProductorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreProductorFocusLost(evt);
            }
        });
        campoNombreProductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreProductorMouseClicked(evt);
            }
        });
        campoNombreProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreProductorActionPerformed(evt);
            }
        });

        checkVisibleContrasena.setText("Visible");
        checkVisibleContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVisibleContrasenaActionPerformed(evt);
            }
        });

        checkVisibleContrasena1.setText("Visible");
        checkVisibleContrasena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVisibleContrasena1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNombreProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registroProductorlbl)
                    .addComponent(nombreLbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoConfirmarClaveProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkVisibleContrasena1))
                            .addComponent(confirmarContrasenaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registrarProductorBtn)
                                .addGap(56, 56, 56)
                                .addComponent(regresarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contrasenaValidaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(correoElectronicoLbl)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoCorreoProductor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(separado2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(contrasenaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(correoValidoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoClaveProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkVisibleContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(registroProductorlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreLbl)
                .addGap(12, 12, 12)
                .addComponent(campoNombreProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(correoElectronicoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCorreoProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(separado2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(correoValidoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(contrasenaLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoClaveProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkVisibleContrasena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(confirmarContrasenaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoConfirmarClaveProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkVisibleContrasena1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contrasenaValidaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registrarProductorBtn)
                        .addComponent(regresarBtn)))
                .addGap(264, 264, 264))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkVisibleContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVisibleContrasenaActionPerformed
        if (this.checkVisibleContrasena.isSelected()) {
            this.campoClaveProductor.setEchoChar((char) 0);
        } else {
            this.campoClaveProductor.setEchoChar('•');
        }
    }//GEN-LAST:event_checkVisibleContrasenaActionPerformed

    private void checkVisibleContrasena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVisibleContrasena1ActionPerformed
         if (this.checkVisibleContrasena.isSelected()) {
            this.campoConfirmarClaveProductor.setEchoChar((char) 0);
        } else {
            this.campoConfirmarClaveProductor.setEchoChar('•');
        }
    }//GEN-LAST:event_checkVisibleContrasena1ActionPerformed

    private void campoCorreoProductorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCorreoProductorFocusGained
       if (validarCampoTextoVacio(campoCorreoProductor, CORREO_DEFAULT)) {
            this.campoCorreoProductor.setForeground(Color.BLACK);
            this.campoCorreoProductor.setText("");
        }
    }//GEN-LAST:event_campoCorreoProductorFocusGained

    private void campoCorreoProductorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCorreoProductorFocusLost
        if (validarCampoTextoVacio(campoCorreoProductor, CORREO_DEFAULT)) {
            this.campoCorreoProductor.setForeground(Color.GRAY);
            this.campoCorreoProductor.setText(CORREO_DEFAULT);
        }
    }//GEN-LAST:event_campoCorreoProductorFocusLost

    private void campoCorreoProductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCorreoProductorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCorreoProductorMouseClicked

    private void campoNombreProductorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreProductorFocusGained
        if (validarCampoTextoVacio(campoNombreProductor, NOMBRE_PRODUCTOR)) {
            this.campoNombreProductor.setForeground(Color.BLACK);
            this.campoNombreProductor.setText("");
        }
    }//GEN-LAST:event_campoNombreProductorFocusGained

    private void campoNombreProductorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreProductorFocusLost
        if (validarCampoTextoVacio(campoNombreProductor, NOMBRE_PRODUCTOR)) {
            this.campoNombreProductor.setForeground(Color.GRAY);
            this.campoNombreProductor.setText(NOMBRE_PRODUCTOR);
        }
    }//GEN-LAST:event_campoNombreProductorFocusLost

    private void campoNombreProductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreProductorMouseClicked
        if (validarCampoTextoVacio(campoNombreProductor, NOMBRE_PRODUCTOR)) {
            this.campoNombreProductor.setForeground(Color.BLACK);
            this.campoNombreProductor.setText("");
        }
    }//GEN-LAST:event_campoNombreProductorMouseClicked

    private void campoNombreProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreProductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreProductorActionPerformed

    private void registrarProductorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProductorBtnActionPerformed
       int i = 0;
        if (validarContrasenasVacio()) {
            if (!validarContrasenaMostrar()) {
                JOptionPane.showMessageDialog(this, "Contraseñas no coinciden", "No puede registrarse", JOptionPane.ERROR_MESSAGE);
                i++;
            }
        } else {

            List<String> camposVacios = this.validarCamposVacios();
            if (!camposVacios.isEmpty()) {
                String mensaje = "Los siguientes campos se encuentran vacíos \n";
                for (String campos : camposVacios) {
                    mensaje += campos + "\n";
                }
                JOptionPane.showMessageDialog(this, mensaje, "No puedes registrarte", JOptionPane.ERROR_MESSAGE);
                i++;
            }
        }
        if (i == 0) {
            //Método registrar
            JOptionPane.showMessageDialog(this, "Registro exitoso", "Nuevo Registro", JOptionPane.INFORMATION_MESSAGE);
            InicioForm b =new InicioForm();
            b.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_registrarProductorBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
      InicioForm i= new InicioForm();
      i.setVisible(true);
      dispose();
    }//GEN-LAST:event_regresarBtnActionPerformed

    private boolean validarContrasenaMostrar() {
        if (validarContrasenasVacio()) {
            if (validarContrasenas()) {
                this.contrasenaValidaLbl.setForeground(Color.GREEN);
                this.contrasenaValidaLbl.setText("Contraseñas coinciden");
                return true;
            } else {
                this.contrasenaValidaLbl.setForeground(Color.red);
                this.contrasenaValidaLbl.setText("Contraseñas no coinciden");
            }
        } else {
            this.contrasenaValidaLbl.setForeground(Color.red);
            this.contrasenaValidaLbl.setText("Contraseñas no coinciden");
        }
        return false;
    }
     
    private List<String> validarCamposVacios() {
        List<String> campos = new LinkedList<>();
        if (this.validarCampoTextoVacio(campoClaveProductor, NOMBRE_PRODUCTOR)) {
            campos.add("- Nombre Productor");
        }
        if (this.validarCampoTextoVacio(campoCorreoProductor, CORREO_DEFAULT)) {
            campos.add("- Correo Electronico");
        }
        if (this.campoClaveProductor.getText().isEmpty() || this.campoClaveProductor.getText().equals(CONTRASENA_DEFAULT)) {
            campos.add("- Contraseña");
        }
        if (this.campoConfirmarClaveProductor.getText().isEmpty() || this.campoConfirmarClaveProductor.getText().equals(CONTRASENA_DEFAULT)) {
            campos.add("- Confirmar contraseña");
        }
        return campos;
    }
    private boolean validarCampoTextoVacio(JTextField campoTexto, String textoDefault) {
        return campoTexto.getText().isEmpty() || campoTexto.getText().equals(textoDefault);
    }
    public static boolean validarCorreo(String correo) {
        String expresionRegular = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
        return correo.matches(expresionRegular);
    }
   
    private boolean validarContrasenas() {
        String contrasena = this.campoClaveProductor.getText();
        String confirmarContrasena = this.campoClaveProductor.getText();
        return contrasena.equals(confirmarContrasena);
    }
    private boolean validarContrasenasVacio() {
        if (this.campoClaveProductor.getText().isEmpty() || this.campoClaveProductor.getText().equals(CONTRASENA_DEFAULT)) {
            return false;
        }
        if (this.campoClaveProductor.getText().isEmpty() || this.campoClaveProductor.getText().equals(CONTRASENA_DEFAULT)) {
            return false;
        }
        return true;
    }

    private boolean validarCorreoMostrar() {
    String correo = campoCorreoProductor.getText();

    if (correo.isEmpty()) {
        correoValidoLbl.setForeground(Color.RED);
        correoValidoLbl.setText("El campo correo está vacío");
        return false;
    } else if (validarCorreo(correo)) {
        correoValidoLbl.setForeground(Color.GREEN);
        correoValidoLbl.setText("El correo es válido");
        return true;
    } else {
        correoValidoLbl.setForeground(Color.RED);
        correoValidoLbl.setText("El correo no es válido");
        return false;
    }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProductorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoClaveProductor;
    private javax.swing.JPasswordField campoConfirmarClaveProductor;
    private javax.swing.JTextField campoCorreoProductor;
    private javax.swing.JTextField campoNombreProductor;
    private javax.swing.JCheckBox checkVisibleContrasena;
    private javax.swing.JCheckBox checkVisibleContrasena1;
    private javax.swing.JLabel confirmarContrasenaLbl;
    private javax.swing.JLabel contrasenaLbl;
    private javax.swing.JLabel contrasenaValidaLbl;
    private javax.swing.JLabel correoElectronicoLbl;
    private javax.swing.JLabel correoValidoLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JButton registrarProductorBtn;
    private javax.swing.JLabel registroProductorlbl;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JSeparator separado2;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador3;
    // End of variables declaration//GEN-END:variables
}
