/**
 * Login.java
 * 30 abr. 2023 13:22:51
 *
 */
package org.itson.presentacion;

import org.itson.presentacion.*;
import java.awt.Color;

/**
 * Descripción de la clase:
 *
 * @author Daniel Armando Peña Garcia ID:229185
 */
public class LoginProductor extends javax.swing.JFrame {

    private String textDefaultUsuario = "Correo/Teléfono";
    private String textDefaultContrasena = "0000000000000000000000";

    /**
     * Creates new form Login
     */
    public LoginProductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        extraPanel = new javax.swing.JPanel();
        usuarioLbl = new javax.swing.JLabel();
        separacionContrasena = new javax.swing.JSeparator();
        usuarioTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        separacionUsuario = new javax.swing.JSeparator();
        contrasenaPsw = new javax.swing.JPasswordField();
        checkVisbleContrasena = new javax.swing.JCheckBox();
        iniciarSesionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        fondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        extraPanel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout extraPanelLayout = new javax.swing.GroupLayout(extraPanel);
        extraPanel.setLayout(extraPanelLayout);
        extraPanelLayout.setHorizontalGroup(
            extraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        extraPanelLayout.setVerticalGroup(
            extraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fondoPanel.add(extraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 430, 561));

        usuarioLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usuarioLbl.setForeground(new java.awt.Color(0, 0, 0));
        usuarioLbl.setText("Usuario");
        fondoPanel.add(usuarioLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 131, -1, -1));
        fondoPanel.add(separacionContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 250, 10));

        usuarioTxt.setBackground(new java.awt.Color(255, 255, 255));
        usuarioTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarioTxt.setForeground(Color.GRAY);
        usuarioTxt.setText(this.textDefaultUsuario);
        usuarioTxt.setBorder(null);
        usuarioTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioTxtFocusLost(evt);
            }
        });
        usuarioTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioTxtMouseClicked(evt);
            }
        });
        usuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTxtActionPerformed(evt);
            }
        });
        fondoPanel.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 250, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Contraseña");
        fondoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        fondoPanel.add(separacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 250, 10));

        contrasenaPsw.setBackground(new java.awt.Color(255, 255, 255));
        contrasenaPsw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contrasenaPsw.setForeground(Color.GRAY);
        contrasenaPsw.setText(this.textDefaultContrasena);
        contrasenaPsw.setBorder(null);
        contrasenaPsw.setEchoChar('•');
        contrasenaPsw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contrasenaPswFocusLost(evt);
            }
        });
        contrasenaPsw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contrasenaPswMouseClicked(evt);
            }
        });
        fondoPanel.add(contrasenaPsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 250, -1));

        checkVisbleContrasena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkVisbleContrasena.setText("Visible");
        checkVisbleContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        checkVisbleContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVisbleContrasenaActionPerformed(evt);
            }
        });
        fondoPanel.add(checkVisbleContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        iniciarSesionBtn.setBackground(new java.awt.Color(204, 255, 204));
        iniciarSesionBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iniciarSesionBtn.setText("Iniciar Sesión");
        fondoPanel.add(iniciarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTxtMouseClicked
        if (this.verificarCampoTextoUsuarioVacio()) {
            this.llenarCampoTextoUsuario("");
            this.cambiarColorCampoTextoUsuario(Color.BLACK);
        }
    }//GEN-LAST:event_usuarioTxtMouseClicked

    private void usuarioTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioTxtFocusLost
        if (verificarCampoTextoUsuarioVacio()) {
            this.llenarCampoTextoUsuario(this.textDefaultUsuario);
            this.cambiarColorCampoTextoUsuario(Color.GRAY);
        }
    }//GEN-LAST:event_usuarioTxtFocusLost

    private void usuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTxtActionPerformed

    private void contrasenaPswMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaPswMouseClicked
        if (this.verificarCampooPassWordFieldVacio()) {
            this.llenarCampoPassWordField("");
            this.cambiarColorCampoPassWordField(Color.BLACK);
        }
    }//GEN-LAST:event_contrasenaPswMouseClicked

    private void contrasenaPswFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasenaPswFocusLost
        if (this.verificarCampooPassWordFieldVacio()) {
            this.llenarCampoPassWordField(this.textDefaultContrasena);
            this.cambiarColorCampoPassWordField(Color.GRAY);
        }
    }//GEN-LAST:event_contrasenaPswFocusLost

    private void checkVisbleContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVisbleContrasenaActionPerformed
        this.alterarVisbleContrasena();
    }//GEN-LAST:event_checkVisbleContrasenaActionPerformed

    private void usuarioTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioTxtFocusGained
        if (this.verificarCampoTextoUsuarioVacio()) {
            this.llenarCampoTextoUsuario("");
            this.cambiarColorCampoTextoUsuario(Color.BLACK);
        }
    }//GEN-LAST:event_usuarioTxtFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginProductor().setVisible(true);
            }
        });
    }

    private String llenarCampoTextoUsuario(String texto) {
        this.usuarioTxt.setText(texto);
        return texto;
    }

    private Color cambiarColorCampoTextoUsuario(Color color) {
        this.usuarioTxt.setForeground(color);
        return color;
    }

    private boolean verificarCampoTextoUsuarioVacio() {
        return this.usuarioTxt.getText().isEmpty() || this.usuarioTxt.getText().equals(this.textDefaultUsuario);
    }

    private String llenarCampoPassWordField(String texto) {
        this.contrasenaPsw.setText(texto);
        return texto;
    }

    private Color cambiarColorCampoPassWordField(Color color) {
        this.contrasenaPsw.setForeground(color);
        return color;
    }

    private boolean verificarCampooPassWordFieldVacio() {
        return this.contrasenaPsw.getText().isEmpty() || this.contrasenaPsw.getText().equals(this.textDefaultContrasena);
    }

    private void alterarVisbleContrasena() {
        if (checkVisbleContrasena.isSelected()) {
            this.contrasenaPsw.setEchoChar((char) 0);
        } else {
            this.contrasenaPsw.setEchoChar('•');
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkVisbleContrasena;
    private javax.swing.JPasswordField contrasenaPsw;
    private javax.swing.JPanel extraPanel;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JButton iniciarSesionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator separacionContrasena;
    private javax.swing.JSeparator separacionUsuario;
    private javax.swing.JLabel usuarioLbl;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables

}
