/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.presentacion.residuo;

import com.dominio.Quimico;
import java.awt.Color;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import org.itson.implementacion.FachadaNegocio;
import org.itson.implementacion.NegocioFactory;
import org.itson.interfaces.INegocio;
import org.itson.interfaces.INegocioQuimico;
import org.itson.presentacion.InicioForm;
import org.itson.presentacion.Productor.PrincipalProductorForm;

/**
 *
 * @author arace
 */
public class RegistroResiduoForm extends javax.swing.JFrame {

    private final String NOMBRE_RESIDUO = "Residuo";
    private List<Quimico> listaQuimicosDisponibles;
    private List<String> listaQuimicosComponentesResiduo;
    INegocio negocio;

    /**
     * Creates new form RegistroResiduoForm
     */
    public RegistroResiduoForm() {
        negocio = new FachadaNegocio();
        listaQuimicosDisponibles = consultarListaQuimicos();
        initComponents();
    }

    private List<Quimico> consultarListaQuimicos() {
        List<Quimico> listaQuimicos;
        listaQuimicos = negocio.consultarQuimicos();
        return listaQuimicos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        registroResiduoLbl = new javax.swing.JLabel();
        separadorRegistroResiduo = new javax.swing.JSeparator();
        campoNombreResiduo = new javax.swing.JTextField();
        separadorNombre = new javax.swing.JSeparator();
        tipoLbl = new javax.swing.JLabel();
        comboTipoResiduo = new javax.swing.JComboBox<>();
        separadorTipo = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        nombreLbl = new javax.swing.JLabel();
        comboResiduosRegistrados = new javax.swing.JComboBox<>();
        guardarResiduoBtn = new javax.swing.JButton();
        regresarBtn = new javax.swing.JButton();
        nombreLbl1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        registroResiduoLbl.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 30)); // NOI18N
        registroResiduoLbl.setText("Registro Residuo");

        campoNombreResiduo.setText(this.NOMBRE_RESIDUO);
        campoNombreResiduo.setBorder(null);
        campoNombreResiduo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreResiduoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreResiduoFocusLost(evt);
            }
        });
        campoNombreResiduo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreResiduoMouseClicked(evt);
            }
        });

        tipoLbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        tipoLbl.setText("Composicion quimica:");

        comboTipoResiduo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        nombreLbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        nombreLbl.setText("Residuos registrados");

        comboResiduosRegistrados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboResiduosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLbl))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(nombreLbl)
                .addGap(41, 41, 41)
                .addComponent(comboResiduosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        guardarResiduoBtn.setText("Continue");
        guardarResiduoBtn.setContentAreaFilled(false);
        guardarResiduoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarResiduoBtnActionPerformed(evt);
            }
        });

        regresarBtn.setText("Back");
        regresarBtn.setContentAreaFilled(false);
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        nombreLbl1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        nombreLbl1.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(regresarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(guardarResiduoBtn)
                        .addGap(173, 173, 173))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoLbl)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(registroResiduoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(separadorRegistroResiduo))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(separadorTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboTipoResiduo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(separadorNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoNombreResiduo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                            .addComponent(nombreLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(registroResiduoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorRegistroResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(nombreLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNombreResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tipoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTipoResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardarResiduoBtn)
                    .addComponent(regresarBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarResiduoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarResiduoBtnActionPerformed


    }//GEN-LAST:event_guardarResiduoBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        PrincipalProductorForm p = new PrincipalProductorForm();
        p.setVisible(true);
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void campoNombreResiduoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreResiduoMouseClicked
//         if (validarCampoTextoVacio(campoNombreResiduo, NOMBRE_RESIDUO)) {
//            this.campoNombreResiduo.setForeground(Color.BLACK);
//            this.campoNombreResiduo.setText("");
//        }
    }//GEN-LAST:event_campoNombreResiduoMouseClicked

    private void campoNombreResiduoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreResiduoFocusGained
//       if (validarCampoTextoVacio(campoNombreResiduo, NOMBRE_RESIDUO)) {
//            this.campoNombreResiduo.setForeground(Color.BLACK);
//            this.campoNombreResiduo.setText("");
//        }
    }//GEN-LAST:event_campoNombreResiduoFocusGained

    private void campoNombreResiduoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreResiduoFocusLost
        if (validarCampoTextoVacio(campoNombreResiduo, NOMBRE_RESIDUO)) {
            this.campoNombreResiduo.setForeground(Color.GRAY);
            this.campoNombreResiduo.setText(NOMBRE_RESIDUO);
        }
    }//GEN-LAST:event_campoNombreResiduoFocusLost

    private boolean validarCampoTextoVacio(javax.swing.JTextField campo, String nombreCampo) {
        if (campo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo vacio " + nombreCampo + " Favor de ingresar el dato.");
            campo.requestFocus();
            return false;
        }
        return true;
    }

    private void agregarQuimicoSeleccionadoListaComponentesResiduo() {
        List<String> quimicos = pasarListaQuimicosString(listaQuimicosDisponibles);
        String quimicoSeleccionado = getQuimicoSeleccionadoDisponibles();
        eliminarQuimicoListaDisponible(quimicoSeleccionado, quimicos);
        agregarQuimicoListaComponenteResiduo(quimicoSeleccionado, listaQuimicosComponentesResiduo);
        cargarComboBoxResiduosDisponibles(listaQuimicosComponentesResiduo);
    }

    private String getQuimicoSeleccionadoDisponibles() {
        String quimicoSeleccionado = comboResiduosRegistrados.getSelectedItem().toString();
        return quimicoSeleccionado;

    }

    private List<String> cargarComboBoxResiduosDisponibles(List<String> quimicos) {
        this.comboResiduosRegistrados.removeAllItems();
        for (int i = 0; i < quimicos.size(); i++) {
            comboResiduosRegistrados.addItem(quimicos.get(i));
        }
        return quimicos;
    }

    private List<String> eliminarQuimicoListaDisponible(String quimicoSeleccionado, List<String> quimicos) {
        quimicos.remove(quimicoSeleccionado);

        return quimicos;

    }

    private List<String> agregarQuimicoListaComponenteResiduo(String quimicoSeleccionado, List<String> quimicos) {
        quimicos.add(quimicoSeleccionado);

        return quimicos;
    }

    private List<String> pasarListaQuimicosString(List<Quimico> quimicos) {
        List<String> listaQuimicoString = new LinkedList<>();
        for (int i = 0; i < quimicos.size(); i++) {
            listaQuimicoString.add(quimicos.get(i).getNombre());
        }
        return listaQuimicoString;
    }

    private List<String> eliminarQuimicoListaComponenteResiduo(String quimicoSeleccionado, List<String> quimicos) {
        quimicos.removeIf(quimico -> quimico.equalsIgnoreCase(quimicoSeleccionado));
        return quimicos;
    }

    private String getQuimicoSeleccionadoListaComponenteResiduo() {
        String listaComponenteResiduo = comboResiduosRegistrados.getSelectedItem().toString();
        return listaComponenteResiduo;

    }

    private List<String> getQuimicoSeleccionadoListaDisponibles() {
        return listaQuimicosComponentesResiduo;
    }

    private String eliminarQuimicoListaComponentesResiduo() {
        String quimicoSeleccionado = getQuimicoSeleccionadoListaComponenteResiduo();
        eliminarQuimicoListaComponenteResiduo(quimicoSeleccionado, listaQuimicosComponentesResiduo);
        return quimicoSeleccionado;
    }

    private List<String> getListaQuimicosComponentesResiduo(String eliminarQuimicoListaComponente) {
        List<String> quimicos = new LinkedList<>(listaQuimicosComponentesResiduo);
        eliminarQuimicoListaComponenteResiduo(eliminarQuimicoListaComponente, quimicos);
        return quimicos;
    }

    private void agregarQuimicoListaDisponibles(String quimicoSeleccionado) {
        listaQuimicosDisponibles.add(new Quimico(quimicoSeleccionado));
    }

    //listaQuimicosDisponibles: agregarQuimicoListaDisponibles()
    private List<String> eliminarQuimicoListaDisponibles(String quimicoSeleccionado) {
        listaQuimicosDisponibles.removeIf(quimico -> quimico.equals(quimicoSeleccionado));
        return eliminarQuimicoListaDisponibles(quimicoSeleccionado);
    }

    public void cargarListaQuimicosDisponibles(List<String> listaQuimicosDisponibles) {
        comboResiduosRegistrados.removeAllItems();
        for (String quimico : listaQuimicosDisponibles) {
            comboResiduosRegistrados.addItem(quimico);
        }
    }

    private void cargarListaQuimicosComponentesResiduo(List<String> quimicos) {
        comboResiduosRegistrados.removeAllItems();
        for (String quimico : quimicos) {
            comboResiduosRegistrados.addItem(quimico);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroResiduoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroResiduoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroResiduoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroResiduoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroResiduoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNombreResiduo;
    private javax.swing.JComboBox<String> comboResiduosRegistrados;
    private javax.swing.JComboBox<String> comboTipoResiduo;
    private javax.swing.JButton guardarResiduoBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel nombreLbl1;
    private javax.swing.JLabel registroResiduoLbl;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JSeparator separadorRegistroResiduo;
    private javax.swing.JSeparator separadorTipo;
    private javax.swing.JLabel tipoLbl;
    // End of variables declaration//GEN-END:variables
}
