/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.presentacion.residuo;

import com.dominio.Productor;
import com.dominio.Quimico;
import com.dominio.Residuo;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import org.itson.excepciones.NegocioException;
import org.itson.excepciones.PresentacionException;
import org.itson.implementacion.FachadaNegocio;
import org.itson.interfaces.INegocio;
import org.itson.presentacion.Productor.PrincipalProductorForm;

/**
 *
 * @author arace
 */
public class RegistroResiduoForm extends javax.swing.JFrame {

    private static RegistroResiduoForm form;
    
    private final String NOMBRE_RESIDUO = "Residuo";
    private final String CODIGO_RESIDUO = "ABC-123";
    INegocio negocio;
    List<Quimico> listaQuimicosDisponibles;
    List<Quimico> listaQuimicosComponenteResiduo;
    Productor productor;

    /**
     * Creates new form RegistroResiduoForm
     */
    private RegistroResiduoForm() {
        negocio = new FachadaNegocio();
        initComponents();
        listaQuimicosDisponibles = consultarListaQuimicosDisponibles();
        llenarComboBoxListaDisponibles(listaQuimicosDisponibles);
    }

    public void iniciarComponentes(){
        this.lblNombreProductor.setText(productor.getNombre());
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        registroResiduoLbl = new javax.swing.JLabel();
        separadorRegistroResiduo = new javax.swing.JSeparator();
        campoNombreResiduo = new javax.swing.JTextField();
        separadorNombre = new javax.swing.JSeparator();
        tipoLbl = new javax.swing.JLabel();
        comboBoxComponenteResiduo = new javax.swing.JComboBox<>();
        separadorTipo = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        nombreLbl = new javax.swing.JLabel();
        comboQuimicosDisponibles = new javax.swing.JComboBox<>();
        btnAgregarQuimicoComponenteResiduo = new javax.swing.JToggleButton();
        lblVerificarCantidadQuimicosSeleccionados = new javax.swing.JLabel();
        nombreLbl1 = new javax.swing.JLabel();
        btnEliminarComponenteResiduo = new javax.swing.JToggleButton();
        lblVerificarCantidadComponentesResiduo = new javax.swing.JLabel();
        nombreLbl2 = new javax.swing.JLabel();
        formatoCodigoResiduo = new javax.swing.JFormattedTextField();
        btnGuardarResiduo = new javax.swing.JToggleButton();
        nombreLbl3 = new javax.swing.JLabel();
        lblNombreProductor = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        registroResiduoLbl.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 30)); // NOI18N
        registroResiduoLbl.setForeground(new java.awt.Color(0, 0, 0));
        registroResiduoLbl.setText("Registro Residuo");

        campoNombreResiduo.setBackground(new java.awt.Color(255, 255, 255));
        campoNombreResiduo.setForeground(Color.GRAY);
        campoNombreResiduo.setText(this.NOMBRE_RESIDUO);
        campoNombreResiduo.setBorder(null);
        campoNombreResiduo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreResiduoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreResiduoFocusLost(evt);
            }
        });
        campoNombreResiduo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreResiduoMouseClicked(evt);
            }
        });

        tipoLbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        tipoLbl.setForeground(new java.awt.Color(0, 0, 0));
        tipoLbl.setText("Composicion quimica:");

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        nombreLbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        nombreLbl.setForeground(new java.awt.Color(0, 0, 0));
        nombreLbl.setText("Químicos disponibles");

        btnAgregarQuimicoComponenteResiduo.setText("Agregar");
        btnAgregarQuimicoComponenteResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarQuimicoComponenteResiduoActionPerformed(evt);
            }
        });

        lblVerificarCantidadQuimicosSeleccionados.setForeground(new java.awt.Color(255, 0, 0));
        lblVerificarCantidadQuimicosSeleccionados.setText("No hay químicos");

        lblVerificarCantidadQuimicosSeleccionados.setVisible(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblVerificarCantidadQuimicosSeleccionados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarQuimicoComponenteResiduo))
                    .addComponent(nombreLbl)
                    .addComponent(comboQuimicosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(nombreLbl)
                .addGap(33, 33, 33)
                .addComponent(comboQuimicosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerificarCantidadQuimicosSeleccionados)
                    .addComponent(btnAgregarQuimicoComponenteResiduo))
                .addContainerGap(380, Short.MAX_VALUE))
        );

        nombreLbl1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        nombreLbl1.setForeground(new java.awt.Color(0, 0, 0));
        nombreLbl1.setText("Nombre:");

        btnEliminarComponenteResiduo.setText("Eliminar");
        btnEliminarComponenteResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarComponenteResiduoActionPerformed(evt);
            }
        });

        lblVerificarCantidadComponentesResiduo.setForeground(new java.awt.Color(255, 0, 0));
        lblVerificarCantidadComponentesResiduo.setText("No hay químicos");

        nombreLbl2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        nombreLbl2.setForeground(new java.awt.Color(0, 0, 0));
        nombreLbl2.setText("Código:");

        formatoCodigoResiduo.setBackground(new java.awt.Color(255, 255, 255));
        formatoCodigoResiduo.setBorder(null);
        formatoCodigoResiduo.setForeground(Color.GRAY);
        try {
            formatoCodigoResiduo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatoCodigoResiduo.setText("ABC-123");
        formatoCodigoResiduo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatoCodigoResiduoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formatoCodigoResiduoFocusLost(evt);
            }
        });
        formatoCodigoResiduo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formatoCodigoResiduoMouseClicked(evt);
            }
        });

        btnGuardarResiduo.setText("GuardarResiduo");
        btnGuardarResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarResiduoActionPerformed(evt);
            }
        });

        nombreLbl3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        nombreLbl3.setForeground(new java.awt.Color(0, 0, 0));
        nombreLbl3.setText("Nombre del Productor:");

        lblNombreProductor.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarResiduo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLbl3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(registroResiduoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(separadorRegistroResiduo)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblVerificarCantidadComponentesResiduo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminarComponenteResiduo))
                                .addComponent(comboBoxComponenteResiduo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoNombreResiduo)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tipoLbl)
                                        .addComponent(nombreLbl1)
                                        .addComponent(nombreLbl2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(separadorNombre)
                                            .addComponent(separadorTipo)
                                            .addComponent(formatoCodigoResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(108, 108, 108)))
                            .addComponent(lblNombreProductor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(registroResiduoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorRegistroResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreLbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreProductor)
                .addGap(34, 34, 34)
                .addComponent(nombreLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNombreResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(separadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(nombreLbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formatoCodigoResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(tipoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxComponenteResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarComponenteResiduo)
                    .addComponent(lblVerificarCantidadComponentesResiduo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarResiduo)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreResiduoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreResiduoMouseClicked
        if (validarCampoTextoVacio(campoNombreResiduo, NOMBRE_RESIDUO)) {
            this.campoNombreResiduo.setForeground(Color.BLACK);
            this.campoNombreResiduo.setText("");
        }
    }//GEN-LAST:event_campoNombreResiduoMouseClicked

    private void campoNombreResiduoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreResiduoFocusGained
        if (validarCampoTextoVacio(campoNombreResiduo, NOMBRE_RESIDUO)) {
            this.campoNombreResiduo.setForeground(Color.BLACK);
            this.campoNombreResiduo.setText("");
        }
    }//GEN-LAST:event_campoNombreResiduoFocusGained

    private void campoNombreResiduoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreResiduoFocusLost
        if (validarCampoTextoVacio(campoNombreResiduo, NOMBRE_RESIDUO)) {
            this.campoNombreResiduo.setForeground(Color.GRAY);
            this.campoNombreResiduo.setText(NOMBRE_RESIDUO);
        }
    }//GEN-LAST:event_campoNombreResiduoFocusLost

    private void btnAgregarQuimicoComponenteResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarQuimicoComponenteResiduoActionPerformed
        try {
            if (comboQuimicosDisponibles.getModel().getSize() == 0) {
                throw new PresentacionException("No hay componentes que eliminar");
            }
            this.agregarQuimicoSeleccionadoListaComponentesResiduo();
        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (comboBoxComponenteResiduo.getModel().getSize() >= 0) {
                this.lblVerificarCantidadComponentesResiduo.setVisible(false);
            }
            if (comboQuimicosDisponibles.getModel().getSize() == 0) {
                this.lblVerificarCantidadQuimicosSeleccionados.setVisible(true);
            } else {
                this.lblVerificarCantidadQuimicosSeleccionados.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnAgregarQuimicoComponenteResiduoActionPerformed

    private void btnEliminarComponenteResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComponenteResiduoActionPerformed
        try {
            if (comboBoxComponenteResiduo.getModel().getSize() == 0) {
                throw new PresentacionException("No hay componentes que eliminar");
            }
            this.eliminarQuimicoSeleccionadoListaComponentesResiduo();
        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (comboBoxComponenteResiduo.getModel().getSize() <= 0) {
                this.lblVerificarCantidadComponentesResiduo.setVisible(true);
            } else {
                this.lblVerificarCantidadComponentesResiduo.setVisible(false);
            }
            if (comboQuimicosDisponibles.getModel().getSize() >= 0) {
                this.lblVerificarCantidadQuimicosSeleccionados.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnEliminarComponenteResiduoActionPerformed

    private void formatoCodigoResiduoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatoCodigoResiduoFocusGained
        if (validarFormattFieldVacio(formatoCodigoResiduo, CODIGO_RESIDUO)) {
            formatoCodigoResiduo.setForeground(Color.BLACK);
            formatoCodigoResiduo.setText("");
        }
    }//GEN-LAST:event_formatoCodigoResiduoFocusGained

    private void formatoCodigoResiduoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formatoCodigoResiduoMouseClicked
        if (validarFormattFieldVacio(formatoCodigoResiduo, CODIGO_RESIDUO)) {
            formatoCodigoResiduo.setForeground(Color.BLACK);
            formatoCodigoResiduo.setText("");
        }
    }//GEN-LAST:event_formatoCodigoResiduoMouseClicked

    private void formatoCodigoResiduoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatoCodigoResiduoFocusLost
        if (validarFormattFieldVacio(formatoCodigoResiduo, CODIGO_RESIDUO)) {
            formatoCodigoResiduo.setForeground(Color.GRAY);
            formatoCodigoResiduo.setText(CODIGO_RESIDUO);
        }
    }//GEN-LAST:event_formatoCodigoResiduoFocusLost

    private void btnGuardarResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarResiduoActionPerformed
        try {
            Residuo residuo = construirResiduo();
            Residuo confirmarResiduo = this.guardarResiduo(residuo);
            if(confirmarResiduo != null){
                JOptionPane.showMessageDialog(this, "Residuo registrado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.cerrarVentana();
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarResiduoActionPerformed

    private Residuo guardarResiduo(Residuo residuo) {
        return negocio.insertarResiduo(residuo);
    }

    private Residuo construirResiduo() {
        
        String codigo = "";
        if (!validarFormattFieldVacio(formatoCodigoResiduo, CODIGO_RESIDUO)) {
            codigo = formatoCodigoResiduo.getText();
        }
        
        String nombre = "";
        if (!validarCampoTextoVacio(campoNombreResiduo, NOMBRE_RESIDUO)) {
            nombre = campoNombreResiduo.getText();
        }

        Residuo residuo = new Residuo();

        List<Quimico> quimicosCompuestos = listaQuimicosComponenteResiduo;
        residuo.setCodigo(codigo);
        residuo.setNombre(nombre);
        residuo.setQuimicos(quimicosCompuestos);
        residuo.setProductor(productor);
        return residuo;
    }

    private boolean validarFormattFieldVacio(JFormattedTextField textField, String textoDefault) {
        if (textField.getText().isBlank() || textField.getText().equals(textoDefault) || textField.getText().equals("   -   ")) {
            return true;
        }
        return false;
    }

    private boolean validarCampoTextoVacio(javax.swing.JTextField campo, String nombreCampo) {
        if (campo.getText().isEmpty() || campo.getText().equals(nombreCampo)) {
            return true;
        }
        return false;
    }

    private void cerrarVentana(){
        this.setVisible(false);
    }
    
    private void abrirPrincipalForm(){
        PrincipalProductorForm principalProductor = PrincipalProductorForm.getInstance();
        principalProductor.iniciarComponentes();
    }
    
    private List<Quimico> consultarListaQuimicosDisponibles() throws PresentacionException {
        try {
            List<Quimico> listaQuimicos = new LinkedList<>();
            listaQuimicos = negocio.consultarQuimicos();
            return listaQuimicos;
        } catch (NegocioException e) {
            throw new PresentacionException(e.getMessage());
        }
    }

    private void llenarComboBoxListaDisponibles(List<Quimico> listaDisponibles) throws PresentacionException {
        try {
            this.comboQuimicosDisponibles.removeAllItems();
            for (Quimico quimico : listaDisponibles) {
                this.comboQuimicosDisponibles.addItem(quimico);
            }

        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, "Algo salió mal\n"
                    + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void agregarQuimicoSeleccionadoListaComponentesResiduo() {
        Quimico quimicoSeleccionado = getQuimicoSeleccionadoListaDisponibles();
        List<Quimico> quimicosSeleccionados = this.eliminarQuimicoListaDisponibles(quimicoSeleccionado);
        this.llenarComboBoxListaDisponibles(quimicosSeleccionados);
        List<Quimico> quimicosComponentesResiduo = this.agregarListaComponenteResiduo(quimicoSeleccionado);
        this.llenarComboBoxComponentesResiduo(quimicosComponentesResiduo);
    }

    private void eliminarQuimicoSeleccionadoListaComponentesResiduo() {
        Quimico quimicoSeleccionado = getQuimicoSeleccionadoListaComponentesResiduo();
        List<Quimico> quimicosSeleccionados = this.agregarQuimicoListaDisponibles(quimicoSeleccionado);
        this.llenarComboBoxListaDisponibles(quimicosSeleccionados);
        List<Quimico> quimicosComponentesResiduo = this.eliminarListaComponenteResiduo(quimicoSeleccionado);
        this.llenarComboBoxComponentesResiduo(quimicosComponentesResiduo);
    }

    private Quimico getQuimicoSeleccionadoListaDisponibles() {
        Quimico quimico = (Quimico) comboQuimicosDisponibles.getSelectedItem();
        return quimico;
    }

    private Quimico getQuimicoSeleccionadoListaComponentesResiduo() {
        Quimico quimico = (Quimico) comboBoxComponenteResiduo.getSelectedItem();
        return quimico;
    }

    private List<Quimico> eliminarQuimicoListaDisponibles(Quimico quimicoSeleccionado) {
        listaQuimicosDisponibles.remove(quimicoSeleccionado);
        return listaQuimicosDisponibles;
    }

    private List<Quimico> agregarListaComponenteResiduo(Quimico quimicoSeleccionado) {
        if (listaQuimicosComponenteResiduo == null) {
            listaQuimicosComponenteResiduo = new LinkedList<>();
        }
        listaQuimicosComponenteResiduo.add(quimicoSeleccionado);
        return listaQuimicosComponenteResiduo;
    }

    private void llenarComboBoxComponentesResiduo(List<Quimico> listaComponentesResiduo) {
        try {
            this.comboBoxComponenteResiduo.removeAllItems();
            for (Quimico quimico : listaComponentesResiduo) {
                this.comboBoxComponenteResiduo.addItem(quimico);
            }

        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, "Algo salió mal\n"
                    + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private List<Quimico> agregarQuimicoListaDisponibles(Quimico quimicoSeleccionado) {
        listaQuimicosDisponibles.add(quimicoSeleccionado);
        return listaQuimicosDisponibles;
    }

    private List<Quimico> eliminarListaComponenteResiduo(Quimico quimicoSeleccionado) {
        if (listaQuimicosComponenteResiduo == null) {
            listaQuimicosComponenteResiduo = new LinkedList<>();
        }
        listaQuimicosComponenteResiduo.remove(quimicoSeleccionado);
        return listaQuimicosComponenteResiduo;
    }

    /**
     * Válida que una lista esté vacia, si la lista está vacía, retorna true, en
     * caso contrarío, regresa false
     *
     * @param lista Lista que se quiere validar
     * @return True si la lista está vacía, false en caso contrario
     */
    private boolean validarListaVacia(List lista) {
        if (lista == null || lista.isEmpty()) {
            //Lista vacía o nula
            return true;
        }
        //Lista no está vacía
        return false;
    }

    public Productor getProductor() {
        return productor;
    }

    public void setProductor(Productor productor) {
        this.productor = productor;
    }
    
    public static RegistroResiduoForm getInstance(){
        if(form == null){
            form = new RegistroResiduoForm();
        }
        return form;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroResiduoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroResiduoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroResiduoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroResiduoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroResiduoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregarQuimicoComponenteResiduo;
    private javax.swing.JToggleButton btnEliminarComponenteResiduo;
    private javax.swing.JToggleButton btnGuardarResiduo;
    private javax.swing.JTextField campoNombreResiduo;
    private javax.swing.JComboBox<Quimico> comboBoxComponenteResiduo;
    private javax.swing.JComboBox<Quimico> comboQuimicosDisponibles;
    private javax.swing.JFormattedTextField formatoCodigoResiduo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNombreProductor;
    private javax.swing.JLabel lblVerificarCantidadComponentesResiduo;
    private javax.swing.JLabel lblVerificarCantidadQuimicosSeleccionados;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel nombreLbl1;
    private javax.swing.JLabel nombreLbl2;
    private javax.swing.JLabel nombreLbl3;
    private javax.swing.JLabel registroResiduoLbl;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JSeparator separadorRegistroResiduo;
    private javax.swing.JSeparator separadorTipo;
    private javax.swing.JLabel tipoLbl;
    // End of variables declaration//GEN-END:variables
}
